service: autobuzzer

provider:
  name: aws
  runtime: java8
  stage: dev
  region: us-west-2

package:
  artifact: build/libs/autobuzzer-dev.jar

functions:
  call-handler:
    handler: com.merricklabs.autobuzzer.Handler
    events:
      - http:
          path: call-responses
          method: post
          response:
            headers:
              Content-Type: "application/xml"
            template: $input.path('$')
