service: autobuzzer

provider:
  name: aws
  runtime: java8
  stage: dev
  region: us-west-2

package:
  artifact: build/libs/autobuzzer-dev.jar

functions:
  call-handler:
    handler: com.merricklabs.autobuzzer.CallHandler
    events:
      - http:
          path: call
          method: post
  sms-handler:
    handler: com.merricklabs.autobuzzer.SmsHandler
    events:
      - http:
          path: sms
          method: post
