micronaut:
  application:
    name: partymode
  security:
    enabled: false

partymode:
  botName: partybot
  firestore:
    projectId:
    collectionName: party-leases
  phone:
    myNumber:
    callboxNumber:

sns:
  region: us-west-2
  enabled: false

googleAssistant:
  appName: partymode

endpoints:
  all:
    enabled: false
  health:
    enabled: true

jackson:
  mapper:
    ACCEPT_CASE_INSENSITIVE_ENUMS: true
  bean-introspection-module: true
  serializationInclusion: NON_NULL
  deserialization:
    failOnUnknownProperties: false

slack:
  token:

logger:
  levels:
    io.github.davidmerrick.partymode: DEBUG

gcp:
  projectId:
