micronaut:
  application:
    name: partymode
  security:
    enabled: false

partymode:
  botName: partybot
  firestore:
    projectId:
    collectionName: party-leases
  sns:
    region: us-west-2
    enabled: false
    topicArn:
  phone:
    myNumber:
    callboxNumber:
  twilio:
    authToken:

endpoints:
  all:
    enabled: false
  health:
    enabled: true

tracing:
  zipkin:
    enabled: false

jackson:
  mapper:
    ACCEPT_CASE_INSENSITIVE_ENUMS: true
  bean-introspection-module: true
  serializationInclusion: NON_NULL
  deserialization:
    failOnUnknownProperties: false

slack:
  token:

logger:
  levels:
    io.github.davidmerrick.partymode: DEBUG
