version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run: apt-get install -y npm
      - run: npm install -G serverless

      # checkout the repository
      - checkout