version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - run: sudo apt-get update && sudo apt-get install -y nodejs npm
      - run: npm install -g serverless

      # checkout the repository
      - checkout